name: Build
on: [push, workflow_dispatch]

jobs:
  build-app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Gradle build
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean build
      - name: Publish test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
  build-infra:
    name: Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      # TODO: change directory once instead of in each step
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          key: ${{ runner.os }}-pip-${{ hashFiles('infrastructure/pulumi/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Create virtual environment
        run: |
          cd infrastructure/pulumi
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          cd infrastructure/pulumi
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd infrastructure/pulumi
          pytest

