name: Build
on: [push]

jobs:
  build-app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Gradle build
        run: ./gradlew build
  build-infra:
    name: Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Change directory
        run: cd infrastructure/pulumi
      - name: Crate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          pwd
          pip install -r requirements.txt
      - name: Run tests
        run: pytest

