name: Build
on: [push]

jobs:
  build:
    name: App
    runs-on: ubuntu-latest
    steps:
      - name: example
        run: echo 'Hello, everyone.'
      - name: Gradle
        run: ./gradlew build

